<?php

namespace Database\Seeders;

use App\Models\Master\Org\Position;
use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    public function run()
    {
        $position = [
            [
                "id"=>1,
                "location_id" => 2,
                "name" => "Kepala Direktur",
                "code" => 1001,
                "level" => "kepala",
            ],
            [
                "id"=>2,
                "location_id" => 2,
                "name" => "Wakil Kepala Direktur",
                "code" => 1002,
                "level" => "wakil kepala",
            ],
            [  "id"=>3,
                "location_id" => 3,
                "name" => "Kepala Bidang Penunjang Medik dan Non Medik",
                "code" => 1003,
                "level" => "kepala",
            ],
            [   "id"=>4,
                "location_id" => 4,
                "name" => "Kepala Bidang Pelayanan Medik dan Keperawatan",
                "code" => 1004,
                "level" => "kepala",
            ],
            [    "id"=>5,
                "location_id" => 6,
                "name" => "Kepala Bidang Pengembangan Sumber Daya Manusia",
                "code" => 1005,
                "level" => "kepala",
            ],
            [    "id"=>6,
                "location_id" => 5,
                "name" => "Kepala Bagian Tata Usaha",
                "code" => 1006,
                "level" => "kepala",
            ],
            [    "id"=>7,
                "location_id" => 7,
                "name" => "Kepala Seksi Penunjang Medik dan Non Medik",
                "code" => 1007,
                "level" => "kepala",
            ],
            [    "id"=>8,
                "location_id" => 8,
                "name" => "Kepala Seksi Sarana dan Prasarana Logistik",
                "code" => 1008,
                "level" => "kepala",
            ],
            [    "id"=>9,
                "location_id" => 11,
                "name" => "Kepala Seksi Pelayanan Medik",
                "code" => 1009,
                "level" => "kepala",
            ],
            [    "id"=>10,
                "location_id" => 12,
                "name" => "Kepala Seksi Pelayanan Keperawatan",
                "code" => 1010,
                "level" => "kepala",
            ],
            [   "id"=>11,
                "location_id" => 13,
                "name" => "Kepala Sub Bagian Program Perencanaan",
                "code" => 1011,
                "level" => "kepala",
            ],
            [    "id"=>12,
                "location_id" => 14,
                "name" => "Kepala Sub Bagian Keuangan",
                "code" => 1012,
                "level" => "kepala",
            ],
            [    "id"=>13,
                "location_id" => 15,
                "name" => "Kepala Sub Bagian Umum dan Kepegawaian",
                "code" => 1013,
                "level" => "kepala",
            ],
            // [    "id"=>14,
            //     "location_id" => 7,
            //     "name" => "Kepala Seksi Penunjang Medik dan Non Medik",
            //     "code" => 1014,
            //     "level" => "kepala",
            // ],
            [    "id"=>14,
                "location_id" => 7,
                "name" => "Kepala Seksi Penunjang Medik dan Non Medik",
                "code" => 1015,
                "level" => "kepala",
            ],
            [    "id"=>15,
                "location_id" => 8,
                "name" => "Kepala Seksi Sarana dan Prasarana Logistik",
                "code" => 1016,
                "level" => "kepala",
            ],
            [    "id"=>16,
                "location_id" => 11,
                "name" => "Kepala Seksi Pelayanan Medik",
                "code" => 1017,
                "level" => "kepala",
            ],
            [    "id"=>17,
                "location_id" => 12,
                "name" => "Kepala Seksi Pelayanan Keperawatan",
                "code" => 1018,
                "level" => "kepala",
            ],
            [    "id"=>18,
                "location_id" => 13,
                "name" => "Kepala Sub Bagian Program Perencanaan",
                "code" => 1019,
                "level" => "kepala",
            ],
            [    "id"=>19,
                "location_id" => 14,
                "name" => "Kepala Sub Bagian Keuangan",
                "code" => 1020,
                "level" => "kepala",
            ],
            [    "id"=>20,
                "location_id" => 15,
                "name" => "Kepala Sub Bagian Umum dan Kepegawaian",
                "code" => 1021,
                "level" => "kepala",
            ],

            [    "id"=>21,
                "location_id" => 7,
                "name" => "Staf Seksi Penunjang Medik dan Non Medik",
                "code" => 1022,
                "level" => "staf",
            ],
            // [    "id"=>23,
            //     "location_id" => 7,
            //     "name" => "Staf Seksi Penunjang Medik dan Non Medik",
            //     "code" => 1023,
            //     "level" => "staf",
            // ],
            [    "id"=>22,
                "location_id" => 8,
                "name" => "Staf Seksi Sarana dan Prasarana Logistik",
                "code" => 1024,
                "level" => "staf",
            ],
            [    "id"=>23,
                "location_id" => 11,
                "name" => "Staf Seksi Pelayanan Medik",
                "code" => 1025,
                "level" => "staf",
            ],
            [    "id"=>24,
                "location_id" => 12,
                "name" => "Staf Seksi Pelayanan Keperawatan",
                "code" => 1026,
                "level" => "staf",
            ],
            [    "id"=>25,
                "location_id" => 13,
                "name" => "Staf Sub Bagian Program Perencanaan",
                "code" => 1027,
                "level" => "staf",
            ],
            [ "id"=>26,
                "location_id" => 14,
                "name" => "Staf Sub Bagian Keuangan",
                "code" => 1028,
                "level" => "staf",
            ],
            [   "id"=>27,
                "location_id" => 15,
                "name" => "Staf Sub Bagian Umum dan Kepegawaian",
                "code" => 1029,
                "level" => "staf",
            ],
            [   "id"=>28,
                "location_id" => 17,
                "name" => "Kepala IPSRS",
                "code" => 1030,
                "level" => "kepala",
            ],
            [
                "id"=>29,
                "location_id" => 16,
                "name" => "Kepala IGD",
                "code" => 1031,
                "level" => "kepala",
            ],
            [   "id"=>30,
                "location_id" => 17,
                "name" => "staf IPSRS",
                "code" => 1032,
                "level" => "staf",

            ],
            [  "id"=>31,
                "location_id" => 16,
                "name" => "staf IGD",
                "code" => 1033,
                "level" => "staf",
            ],
            [
                "id"=>32,
                "location_id" => 9, //belum
                "name" => "Kepala Seksi PSDM dan Diklat",
                "code" => 1034,
                "level" => "kepala",
            ],
            [   "id"=>33,
                "location_id" => 10, //belum
                "name" => "Kepala Seksi Humas",
                "code" => 1035,
                "level" => "kepala",
            ],
            [
                "id"=>34,
                "location_id" => 9, //belum
                "name" => "Staf Seksi PSDM dan Diklat",
                "code" => 1036,
                "level" => "staf",
            ],
            [   "id"=>35,
                "location_id" => 10, //belum
                "name" => "Staf Seksi Humas",
                "code" => 1037,
                "level" => "staf",
            ],
            
        ];

        $this->generate($position);
    }

    public function generate($position)
    {
        ini_set("memory_limit", -1);

        foreach ($position as $val) {
            $position              = Position::firstOrNew(['code' => $val['code']]);
            $position->id          = $val['id'];
            $position->location_id = $val['location_id'] ?? NULL;
            $position->name        = $val['name'];
            $position->code        = $val['code'];
            $position->level        = $val['level'] ?? NULL;
            $position->created_by = 1;
            $position->created_at  = \Carbon\Carbon::now();;
            $position->save();
        }
    }

    public function countActions($data)
    {
        $count = count($data);

        return $count;
    }
}
